# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: false
default_language_version:
  python: python3
default_stages:
  - commit
  - push
minimum_pre_commit_version: 3.6.2
repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [toml]
        args: [--order-by-type]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf] # LF (Unix-style)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py38-plus, --keep-runtime-typing]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
      - id: ruff
        types_or: [python, jupyter]
        args: [--fix, --exit-non-zero-on-fix]
