# path definitions
RESULTS_PATH: "/Users/niklaskiermeyer/Desktop/Codespace/DruxAI/results/training"
PROJECT_PATH: "/Users/niklaskiermeyer/Desktop/Codespace/DruxAI"
DATA_PATH: "/Users/niklaskiermeyer/Desktop/Codespace/DruxAI/data/preprocessed"

# wandb logging
SWEEPNAME: "DruxAI Hyperparameter Sweep"

# fixed params
GRAD_CLIP: 1.0
NUM_WORKERS: 6
