# path definitions
RESULTS_PATH: "/Users/niklaskiermeyer/Desktop/Codespace/DruxAI/results/training"
DATA_PATH: "/Users/niklaskiermeyer/Desktop/Codespace/DruxAI/data/preprocessed"

# wandb logging
EXPERIMENT_NAME: "DruxAI Training Run"

# fixed params
GRAD_CLIP: 1.0
NUM_WORKERS: 6
